title: jeffcaldwell.ca
url: "https://www.jeffcaldwell.ca"
description: "Software Developer and Professor of Business and Information Technology"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  blogs:
    output: true  # Generates individual blog post pages
    permalink: /blog/:name/
    sort_by: date