title: jeffcaldwell.ca
url: "https://jeffcaldwell.ca"
description: "Software Developer and Professor of Business and Information Technology"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  pings:
    output: false  # Prevents individual ping pages from being generated
    sort_by: date
  blogs:
    output: true  # Generates individual blog post pages
    permalink: /blog/:name/