collections:
  pings:
    output: false  # Prevents individual ping pages from being generated
    sort_by: date
  blogs:
    output: true  # Generates individual blog post pages
    permalink: /blog/:name/